
services:
  comments-api:
    build: ./comments-api
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - PORT=${EXTERNAL_PORT}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TELEGRAM_NOTIFY_URL=${TELEGRAM_NOTIFY_URL:-http://localhost:8080/notify}
    depends_on:
      - mongo
    networks:
      - comments-net
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - comments-net
    restart: unless-stopped

  directus:
    image: directus/directus:latest
    command: sh -c "node cli.js schema apply /directus/extensions/schema.yaml --yes && node docker-entrypoint.cjs"
    ports:
      - 8055:8055
    volumes:
      - directus_database:/directus/database
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
      - ./directus-schema.yaml:/directus/extensions/schema.yaml
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'
      ADMIN_EMAIL: '${ADMIN_DIRECTUS_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_DIRECTUS_PASSWORD}'

      # Database Config (SQLite for maximum lightness)
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      
      # Cloudflare R2 Config
      # By default it saves locally, but if R2 variables are present, it uses them
      STORAGE_LOCATIONS: 'r2'
      STORAGE_R2_DRIVER: 's3'
      STORAGE_R2_KEY: '${R2_ACCESS_KEY_ID:-}'
      STORAGE_R2_SECRET: '${R2_SECRET_ACCESS_KEY:-}'
      STORAGE_R2_BUCKET: '${R2_BUCKET_NAME:-}'
      STORAGE_R2_ENDPOINT: 'https://${R2_ACCOUNT_ID:-}.r2.cloudflarestorage.com'
      STORAGE_R2_REGION: 'auto'
      
    networks:
      - comments-net
    restart: unless-stopped

networks:
  comments-net:

volumes:
  mongo_data:
  directus_database:
  directus_uploads:
  directus_extensions:
